version: "2"

tasks:
  default:
    cmds:
      - go build -o server.exe ./server/
      - ./server.exe

  services:
    cmds:
      - docker-compose -f .\docker-compose.dev.yml up -d

  generate:
    cmds:
      # Calling the Go generator from the Prisma CLI is not supported yet...
      # - npx @prisma/cli generate
      # so we call it directly:
      - go run github.com/prisma/prisma-client-go generate
      # Also generate TypeScript type declarations from some backend structs.
      - go run types.go

  migrate:
    cmds:
      - npx @prisma/cli migrate save --experimental
      - npx @prisma/cli migrate up --experimental

  dbuild:
    cmds:
      - docker build -t southclaws/openmp-index .

  upload-assets:
    dir: frontend/public
    cmds:
      - mc cp --recursive images omp/assets

  build-email-templates:
    dir: emails
    cmds:
      - npm run build
